### ISSUE TITLE
Rename repo to pathspec

### ISSUE THREAD

**Issue by pykong** [cpburnz/python-pathspec#35]
@cpburnz I feel this repo should be just called `pathspec` the same way you would install it from PyPI, as it is not the same as `python-path-specification`.

Minor detail, but it confused me.

**Comment by cpburnz** [comment]
@pykong I had wondered if the slight difference in the name would cause confusion. Thanks for letting me know. I'll look into Github's renaming capabilities.

**Comment by cpburnz** [comment]
I've renamed the project to `python-pathspec` because that best reflects it's a Python library named "pathspec".
