### ISSUE TITLE
Why doesn't !<path> act the same as .gitignore? 

### ISSUE THREAD

**Issue by darrenhaken** [cpburnz/python-pathspec#39]
When using .gitignore I could to the following:

```
*.log
!important/*.log
trace.*
```
This would exclude all log files but then include important/*log. Pathspec doesn't work this way, was this intentional?

**Comment by caleb-partsgiant** [comment]
Can you provide an example file tree, and the results that differ from what you expect? My example below works for me. Perhaps there's an edge case I'm missing.

---


Say you have the following file tree:

```
a.log
b.txt
important
important/d.log
important/e.txt
trace.c
```

And match against that using:

```python
import pathspec

spec = pathspec.PathSpec.from_lines('gitwildmatch', """
*.log
!important/*.log
trace.*
""".splitlines())

matched_files = set(spec.match_tree_files("."))
for path in matched_files:
    print(path)
```

That will output:

```
a.log
trace.c
```

If you remove those matched files against the whole tree:

```
import pathspec.util

all_files = set(pathspec.util.iter_tree_files("."))
for path in all_files - matched_files:
    print(path)
```

That will finally output:

```
b.txt
important/d.log
important/e.txt
```

I think that matches the desired behavior of the ".gitignore" file you described.

**Comment by cpburnz** [comment]
Can you provide an example file tree, and the results that differ from what you expect? My example below works for me. Perhaps there's an edge case I'm missing.

---


Say you have the following file tree:

```
a.log
b.txt
important
important/d.log
important/e.txt
trace.c
```

And match against that using:

```python
import pathspec

spec = pathspec.PathSpec.from_lines('gitwildmatch', """
*.log
!important/*.log
trace.*
""".splitlines())

matched_files = set(spec.match_tree_files("."))
for path in matched_files:
    print(path)
```

That will output:

```
a.log
trace.c
```

If you remove those matched files against the whole tree:

```
import pathspec.util

all_files = set(pathspec.util.iter_tree_files("."))
for path in all_files - matched_files:
    print(path)
```

That will finally output:

```
b.txt
important/d.log
important/e.txt
```

I think that matches the desired behavior of the ".gitignore" file you described.

**Comment by cpburnz** [comment]
@darrenhaken Are you still having this problem?

**Comment by cpburnz** [comment]
I'm closing this due to lack of feedback about the issue.
