### ISSUE TITLE
Exports are considered private

### ISSUE THREAD

**Issue by Avasam** [cpburnz/python-pathspec#68]
The imports in `__init__.py` are considered private unless they are explicitly re-exported using the `as` keyword.
![image](https://user-images.githubusercontent.com/1350584/204165077-2f136271-2f8b-4b00-a124-84ae6cfbb110.png)

**Comment by cpburnz** [comment]
@Avasam  The top level private imports have been marked as belonging to the public interface using `__all__`. According to pyright's [Typing Guidance for Python Libraries](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md), adding the private imports to `__all__` should satisfy Pylance/pyright.
