### ISSUE TITLE
`'Self'` string literal type is `Unknown` in pyright

### ISSUE THREAD

**Issue by Avasam** [cpburnz/python-pathspec#70]
![image](https://user-images.githubusercontent.com/1350584/204165759-d9c1afa2-8889-46f1-8419-7a7d4ebdbf87.png)

non string literal type `Self` works, but I believe it has issues with mypy iirc. You can use the same workaround as typeshed does by defining a `TypeVar`: `Self = TypeVar("Self")`

**Comment by cpburnz** [comment]
@Avasam Thanks for pointing this out as well. My adhoc method was messy.
