### ISSUE TITLE
Please consider switching the build-system to flit_core to ease setuptools bootstrap

### ISSUE THREAD

**Issue by mgorny** [cpburnz/python-pathspec#72]
Could you please consider switching the build system from setuptools to [flit_core](https://pypi.org/project/flit-core/)? This would help Linux distributions such as Gentoo avoid cyclic dependencies that cause bootstrapping unbundled setuptools a real pain. If you agree, I can submit a pull request doing the conversion.

The problem is that the most recent release of setuptools (66.0.0) started using platformdirs. platformdirs use the hatchling build backend which in turn requires this package. This creates a dependency cycle that we can't install setuptools before installing platformdirs, and we can't build platformdirs before all of hatchling's dependencies are installed, and we effectively end up needing setuptools to build them.

flit_core is a "no dependencies [except for tomli, on Python < 3.11]"  by design, so it makes bootstrapping packages much easier.

**Comment by ofek** [comment]
More context:

- https://github.com/pfmoore/editables/issues/22
- https://github.com/platformdirs/platformdirs/issues/128
- https://github.com/pytest-dev/pluggy/issues/372

**Comment by cpburnz** [comment]
@mgorny Thanks for bring this to my attention. I want to make sure Linux distributions can package *pathspec* without too much trouble. I already do some preprocessing to generate a *setup.cfg* to support old versions of *setuptools* for Fedora. I'm interested in a pull-request switching to *flit_core*.

The links provided by @ofek were useful. After some digging it looks like core PyPA packaging projects (e.g., [build](https://github.com/pypa/build/blob/main/pyproject.toml)) use *flit_core* for the build system.

**Comment by mgorny** [comment]
Filed as #73.

**Comment by cpburnz** [comment]
@mgorny Version 0.11.0 is now released which uses the flit_core backend.

**Comment by mgorny** [comment]
Thank you!
