### ISSUE TITLE
On bracket expression negation

### ISSUE THREAD

**Issue by tomruk** [cpburnz/python-pathspec#77]
`^` is escaped, but it works with gitignore.

To test it:
```shell
mkdir test && cd test
git init
echo 'a[^b]c' > .gitignore
touch abc azc
git status -u --ignored
```

Notice that abc doesn't match but azc does match. pathspec's behavior with `^` is inconsistent with Git.

I read:
https://github.com/cpburnz/python-pathspec/blob/6fd6bee628f5f2746ac46939b13fd127941a73f9/pathspec/patterns/gitwildmatch.py#L313

But I didn't understand why would you prefer to be compatible with POSIX and Python's `fnmatch.translate` when you could be compatible with gitignore itself. May I ask what led you to the decision to escape `^`?

**Comment by cpburnz** [comment]
From the comment I have there:

> POSIX declares that the regex bracket expression negation
> "[^...]" is undefined in a glob pattern. Python's
> `fnmatch.translate()` escapes the caret ('^') as a
>  literal. To maintain consistency with undefined behavior,
>  I am escaping the '^' as well.

My intent was to maintain the undefined behavior I was aware of. It does makes more sense to follow Git's behavior.

**Comment by tomruk** [comment]
Okay, let's follow Git's behavior: https://github.com/cpburnz/python-pathspec/pull/78
